apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: colepago-backend-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    nginx.ingress.kubernetes.io/proxy-read-timeout: "120"
    nginx.ingress.kubernetes.io/proxy-body-size: "10m"
spec:
  ingressClassName: nginx
  rules:
  - host: api.drsrv.net.ar
    http:
      paths:
      - path: /(.*)
        pathType: ImplementationSpecific
        backend:
          service:
            name: colepago-backend
            port:
              number: 8282
  tls:
  - hosts:
    - api.drsrv.net.ar
    secretName: api-tls-secret
